version: '3.8'

services:
  mongodb:
    container_name: mongo_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: testdb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - node-network

  node-app:
    container_name: node_app
    tty: true
    image: node18.17.0-template:v1
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/app_db
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    networks:
      - node-network

  mongo-express:
    container_name: mongo_express_ui
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
      ME_CONFIG_MONGODB_URL: mongodb://root:mongopass@mongo_db:27017/
    networks:
      - node-network

networks:
  node-network:
    driver: bridge


#mongodb://root:mongopass@localhost:27017/testdb
#mongodb+srv://root:mongopass@localhost:27017/testdb
#mongodb://root:mongopass@localhost:27017/WebshopDB
  